import type { PartDef } from '../types.js';

/**
 * Built-in part catalog. The PocketBase backend seeds this same list into
 * `takeon_parts` so servers can rebalance or extend it; the engine accepts
 * any PartDef[] at load time.
 */
export const PARTS: PartDef[] = [
  // ── Chassis ────────────────────────────────────────────────────────────
  {
    id: 'chassis-scout',
    category: 'chassis',
    name: 'Scout Frame',
    tier: 1,
    mass: 40,
    cost: 200,
    description: 'Light aluminium frame. Two module slots, modest armour, 10-unit sample bin.',
    stats: { slots: 2, durability: 80, cargoCapacity: 10 },
  },
  {
    id: 'chassis-lab',
    category: 'chassis',
    name: 'Field Lab',
    tier: 2,
    mass: 70,
    cost: 520,
    description: 'Mid-size science platform with three module slots and a 16-unit bin.',
    stats: { slots: 3, durability: 130, cargoCapacity: 16 },
  },
  {
    id: 'chassis-hauler',
    category: 'chassis',
    name: 'Hauler',
    tier: 3,
    mass: 110,
    cost: 950,
    description: 'Heavy mining chassis. Four slots, thick plating, 30-unit bin.',
    stats: { slots: 4, durability: 200, cargoCapacity: 30 },
  },
  // ── Wheels ─────────────────────────────────────────────────────────────
  {
    id: 'wheels-rigid',
    category: 'wheels',
    name: 'Rigid Wheels',
    tier: 1,
    mass: 20,
    cost: 120,
    description: 'Simple machined wheels. Fast on flats, poor climbers.',
    stats: { speed: 2.6, maxClimb: 1, grip: 0.3 },
  },
  {
    id: 'wheels-rocker',
    category: 'wheels',
    name: 'Rocker-Bogie',
    tier: 2,
    mass: 32,
    cost: 380,
    description: 'The classic. Steady over rocks, climbs single-voxel steps with ease.',
    stats: { speed: 2.2, maxClimb: 2, grip: 0.6 },
  },
  {
    id: 'wheels-tracks',
    category: 'wheels',
    name: 'Treaded Tracks',
    tier: 3,
    mass: 55,
    cost: 720,
    description: 'Slow but nearly unstoppable. Best grip, best climb.',
    stats: { speed: 1.7, maxClimb: 3, grip: 0.85 },
  },
  // ── Power ──────────────────────────────────────────────────────────────
  {
    id: 'power-solar-s',
    category: 'power',
    name: 'Solar Wing S',
    tier: 1,
    mass: 12,
    cost: 150,
    description: 'Folding photovoltaic wing. Great in sunlight, useless at night.',
    stats: { solarRate: 2.4 },
  },
  {
    id: 'power-solar-xl',
    category: 'power',
    name: 'Solar Array XL',
    tier: 2,
    mass: 26,
    cost: 430,
    description: 'Twin high-efficiency arrays for power-hungry builds.',
    stats: { solarRate: 4.6 },
  },
  {
    id: 'power-rtg',
    category: 'power',
    name: 'RTG Core',
    tier: 3,
    mass: 45,
    cost: 900,
    description: 'Radioisotope generator. Steady trickle day and night, anywhere.',
    stats: { rtgRate: 1.6, solarRate: 0 },
  },
  // ── Battery ────────────────────────────────────────────────────────────
  {
    id: 'batt-cell',
    category: 'battery',
    name: 'Li-Cell Pack',
    tier: 1,
    mass: 10,
    cost: 100,
    description: 'Basic 60 unit battery pack.',
    stats: { batteryCapacity: 60 },
  },
  {
    id: 'batt-stack',
    category: 'battery',
    name: 'Stacked Cells',
    tier: 2,
    mass: 22,
    cost: 320,
    description: 'A 120 unit stack with better cold tolerance.',
    stats: { batteryCapacity: 120 },
  },
  {
    id: 'batt-vault',
    category: 'battery',
    name: 'Power Vault',
    tier: 3,
    mass: 40,
    cost: 680,
    description: '220 units of deep storage for long nights.',
    stats: { batteryCapacity: 220 },
  },
  // ── Tools (module) ─────────────────────────────────────────────────────
  {
    id: 'tool-scoop',
    category: 'tool',
    name: 'Sample Scoop',
    tier: 1,
    mass: 8,
    cost: 140,
    description: 'Digs soft surface material. Struggles with hard rock.',
    stats: { miningPower: 1, miningEnergy: 3 },
  },
  {
    id: 'tool-drill',
    category: 'tool',
    name: 'Percussive Drill',
    tier: 2,
    mass: 24,
    cost: 460,
    description: 'Chews through rock and ore at a fair energy price.',
    stats: { miningPower: 2.5, miningEnergy: 5 },
  },
  {
    id: 'tool-laser',
    category: 'tool',
    name: 'Ablation Laser',
    tier: 3,
    mass: 30,
    cost: 880,
    description: 'Vaporises anything, fast — if you can feed it.',
    stats: { miningPower: 4.5, miningEnergy: 9 },
  },
  // ── Cameras (module) ───────────────────────────────────────────────────
  {
    id: 'cam-nav',
    category: 'camera',
    name: 'NavCam',
    tier: 1,
    mass: 4,
    cost: 90,
    description: 'Utility camera. Enough to document what you find.',
    stats: { photoQuality: 3, photoEnergy: 1.5 },
  },
  {
    id: 'cam-pano',
    category: 'camera',
    name: 'PanoCam',
    tier: 2,
    mass: 9,
    cost: 300,
    description: 'Wide sensor with colour calibration targets.',
    stats: { photoQuality: 6, photoEnergy: 2.5 },
  },
  {
    id: 'cam-science',
    category: 'camera',
    name: 'ChemCam Pro',
    tier: 3,
    mass: 14,
    cost: 640,
    description: 'Publication-grade imaging. Discoveries score highest with it.',
    stats: { photoQuality: 10, photoEnergy: 4 },
  },
  // ── Scanners (module) ──────────────────────────────────────────────────
  {
    id: 'scan-short',
    category: 'scanner',
    name: 'Proximity Sounder',
    tier: 1,
    mass: 6,
    cost: 160,
    description: 'Pings anomalies within 10 tiles.',
    stats: { scanRadius: 10, scanEnergy: 4 },
  },
  {
    id: 'scan-deep',
    category: 'scanner',
    name: 'Deep Radar',
    tier: 2,
    mass: 16,
    cost: 520,
    description: 'Long-range sweep, 22 tile radius.',
    stats: { scanRadius: 22, scanEnergy: 8 },
  },
  // ── Cargo (module) ─────────────────────────────────────────────────────
  {
    id: 'cargo-crate',
    category: 'cargo',
    name: 'Sample Crate',
    tier: 1,
    mass: 10,
    cost: 110,
    description: 'Holds 20 units of mined material.',
    stats: { cargoCapacity: 20 },
  },
  {
    id: 'cargo-hold',
    category: 'cargo',
    name: 'Bulk Hold',
    tier: 2,
    mass: 28,
    cost: 360,
    description: 'Holds 60 units. Heavy when full — plan your power.',
    stats: { cargoCapacity: 60 },
  },
  // ── Fuel (module) ──────────────────────────────────────────────────────
  {
    id: 'fuel-aux',
    category: 'fuel',
    name: 'Aux Fuel Tank',
    tier: 1,
    mass: 15,
    cost: 130,
    description: '40 units of lander fuel. More reach, more targets.',
    stats: { fuelCapacity: 40 },
  },
  {
    id: 'fuel-long',
    category: 'fuel',
    name: 'Long-Haul Tank',
    tier: 2,
    mass: 34,
    cost: 400,
    description: '100 units of fuel for the far destinations.',
    stats: { fuelCapacity: 100 },
  },
];

export function getPart(id: string, catalog: PartDef[] = PARTS): PartDef | undefined {
  return catalog.find((p) => p.id === id);
}
