/**
 * GENERATED by scripts/fetch-dem.mjs alongside generated.ts — do not edit.
 *
 * This is the regression tripwire for real planetary data: it lists the DEM
 * patch ids that generated.ts is expected to embed. The two files are written
 * together by the fetch script, so if generated.ts is ever reverted to an
 * empty object on its own (merge accident, bad regen), the dem test fails
 * loudly instead of the engine silently falling back to procedural terrain.
 *
 * Empty right now because the fetch has not yet been run from an environment
 * that can reach trek.nasa.gov. Run `node scripts/fetch-dem.mjs` and commit
 * both files to arm it.
 */
export const EXPECTED_DEM_IDS: string[] = [];
