/**
 * Real-terrain DEM registry.
 *
 * A DEM patch is a small normalised height grid (values 0..1) sampled from a
 * real planetary elevation model — NASA MGS MOLA for Mars, LRO LOLA for the
 * Moon. Patches are generated by `scripts/fetch-dem.mjs` (requires network
 * access to trek.nasa.gov), which rewrites `generated.ts` next to this file.
 *
 * When a body's `dem` id has no registered patch the terrain generator falls
 * back to fully procedural relief, so the game runs identically with or
 * without the data present.
 */

export interface DemPatch {
  /** Source attribution, e.g. "NASA MGS MOLA 463m, Jezero crater region". */
  source: string;
  /** Grid edge length (square). */
  size: number;
  /** Row-major normalised heights, length size*size, 0..1. */
  heights: number[];
}

import { GENERATED_DEMS } from './generated.js';

const DEMS = new Map<string, DemPatch>(Object.entries(GENERATED_DEMS));

export function registerDem(id: string, patch: DemPatch): void {
  DEMS.set(id, patch);
}

export function getDem(id: string): DemPatch | undefined {
  return DEMS.get(id);
}

/** Bilinear sample of a patch at normalised coords u,v in [0,1]. */
export function sampleDem(patch: DemPatch, u: number, v: number): number {
  const s = patch.size;
  const x = Math.min(s - 1.001, Math.max(0, u * (s - 1)));
  const y = Math.min(s - 1.001, Math.max(0, v * (s - 1)));
  const x0 = Math.floor(x);
  const y0 = Math.floor(y);
  const fx = x - x0;
  const fy = y - y0;
  const h = patch.heights;
  const a = h[y0 * s + x0];
  const b = h[y0 * s + x0 + 1];
  const c = h[(y0 + 1) * s + x0];
  const d = h[(y0 + 1) * s + x0 + 1];
  return a + (b - a) * fx + (c - a) * fy + (a - b - c + d) * fx * fy;
}
