// Sample real planetary elevation into engine DEM patches.
//
//   node scripts/fetch-dem.mjs
//
// Downloads DEM tiles from the NASA Trek WMTS services (public, no key):
//   Mars: MGS MOLA global DEM mosaic (463m/px)  — Jezero crater region
//   Moon: LRO LOLA global DEM (256ppd)          — Mare Imbrium region
// decodes them with the bundled Chromium (no native image deps), normalises
// to a 96x96 height grid, and rewrites
// packages/engine/src/world/dem/generated.ts.
//
// Requires network access to trek.nasa.gov. Rebuild the engine afterwards.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const here = dirname(fileURLToPath(import.meta.url));

const PATCHES = [
  {
    id: 'mars-jezero',
    source: 'NASA MGS MOLA DEM mosaic 463m (Trek), Jezero crater region',
    // WMTS: {z}/{row}/{col} — z4 tile covering ~Jezero (18.4N, 77.7E).
    url: 'https://trek.nasa.gov/tiles/Mars/EQ/Mars_MGS_MOLA_DEM_mosaic_global_463m/1.0.0/default/default028mm/4/5/22.jpg',
  },
  {
    id: 'moon-imbrium',
    source: 'NASA LRO LOLA DEM 256ppd (Trek), Mare Imbrium region',
    url: 'https://trek.nasa.gov/tiles/Moon/EQ/LRO_LOLA_DEM_Global_256ppd_v06/1.0.0/default/default028mm/4/3/12.jpg',
  },
];

const SIZE = 96;

// Honour an outbound proxy (e.g. sandboxed/CI environments front HTTPS with
// one). Playwright's request API + the MITM CA need explicit opt-in.
const proxyServer = process.env.HTTPS_PROXY ?? process.env.https_proxy;
const browser = await chromium.launch({
  executablePath: process.env.PLAYWRIGHT_CHROMIUM ?? '/opt/pw-browsers/chromium',
  proxy: proxyServer ? { server: proxyServer } : undefined,
});
const context = await browser.newContext({ ignoreHTTPSErrors: !!proxyServer });
const page = await context.newPage();

const chunks = [];
for (const p of PATCHES) {
  console.log(`fetching ${p.id} …`);
  // Fetch the tile bytes via Playwright's request API — it follows the
  // context proxy and is not subject to page CORS (an in-page fetch from
  // about:blank would be blocked unless the server sends CORS headers).
  const res = await context.request.get(p.url).catch((err) => {
    throw new Error(
      `${p.url} unreachable (${err.message}). trek.nasa.gov must be reachable ` +
        `from this machine — sandboxed environments may need it added to the ` +
        `network allowlist, or run this script locally.`,
    );
  });
  if (!res.ok()) throw new Error(`${p.url} -> HTTP ${res.status()}`);
  const b64 = (await res.body()).toString('base64');
  const grid = await page.evaluate(
    async ({ b64, size }) => {
      const bytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
      const bmp = await createImageBitmap(new Blob([bytes], { type: 'image/jpeg' }));
      const c = new OffscreenCanvas(size, size);
      const g = c.getContext('2d');
      g.drawImage(bmp, 0, 0, size, size);
      const d = g.getImageData(0, 0, size, size).data;
      const out = new Array(size * size);
      let min = Infinity;
      let max = -Infinity;
      for (let i = 0; i < size * size; i++) {
        // DEM tiles encode elevation as luminance.
        const v = 0.299 * d[i * 4] + 0.587 * d[i * 4 + 1] + 0.114 * d[i * 4 + 2];
        out[i] = v;
        if (v < min) min = v;
        if (v > max) max = v;
      }
      const range = Math.max(1, max - min);
      return out.map((v) => Math.round(((v - min) / range) * 1000) / 1000);
    },
    { b64, size: SIZE },
  );
  chunks.push(
    `  '${p.id}': {\n    source: ${JSON.stringify(p.source)},\n    size: ${SIZE},\n    heights: ${JSON.stringify(grid)},\n  },`,
  );
  console.log(`  ok (${grid.length} samples)`);
}

await browser.close();

const file = `/**
 * GENERATED by scripts/fetch-dem.mjs — do not edit by hand.
 * Sources: NASA Trek WMTS (MGS MOLA, LRO LOLA). Public domain (NASA).
 */
import type { DemPatch } from './index.js';

export const GENERATED_DEMS: Record<string, DemPatch> = {
${chunks.join('\n')}
};
`;
const out = join(here, '..', 'packages', 'engine', 'src', 'world', 'dem', 'generated.ts');
writeFileSync(out, file);

// The expectation manifest is written separately so a lone revert of
// generated.ts back to `{}` trips the dem regression test.
const expected = `/**
 * GENERATED by scripts/fetch-dem.mjs alongside generated.ts — do not edit.
 * Lists the DEM patch ids generated.ts must embed; the dem test fails if any
 * are missing, so real data can't silently regress to procedural fallback.
 */
export const EXPECTED_DEM_IDS: string[] = ${JSON.stringify(PATCHES.map((p) => p.id))};
`;
const expectedOut = join(here, '..', 'packages', 'engine', 'src', 'world', 'dem', 'expected.ts');
writeFileSync(expectedOut, expected);

console.log('wrote', out);
console.log('wrote', expectedOut, '- rebuild the engine to embed the patches.');
