// Sample real planetary elevation into engine DEM patches.
//
//   node scripts/fetch-dem.mjs
//
// Downloads DEM tiles from the NASA Trek WMTS services (public, no key):
//   Mars: MGS MOLA global DEM mosaic (463m/px)  — Jezero crater region
//   Moon: LRO LOLA global DEM (256ppd)          — Mare Imbrium region
// decodes them with the bundled Chromium (no native image deps), normalises
// to a 96x96 height grid, and rewrites
// packages/engine/src/world/dem/generated.ts.
//
// Requires network access to trek.nasa.gov. Rebuild the engine afterwards.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

const here = dirname(fileURLToPath(import.meta.url));

const PATCHES = [
  {
    id: 'mars-jezero',
    source: 'NASA MGS MOLA DEM mosaic 463m (Trek), Jezero crater region',
    // WMTS: {z}/{row}/{col} — z4 tile covering ~Jezero (18.4N, 77.7E).
    url: 'https://trek.nasa.gov/tiles/Mars/EQ/Mars_MGS_MOLA_DEM_mosaic_global_463m/1.0.0/default/default028mm/4/5/22.jpg',
  },
  {
    id: 'moon-imbrium',
    source: 'NASA LRO LOLA DEM 256ppd (Trek), Mare Imbrium region',
    url: 'https://trek.nasa.gov/tiles/Moon/EQ/LRO_LOLA_DEM_Global_256ppd_v06/1.0.0/default/default028mm/4/3/12.jpg',
  },
];

const SIZE = 96;

const browser = await chromium.launch({
  executablePath: process.env.PLAYWRIGHT_CHROMIUM ?? '/opt/pw-browsers/chromium',
});
const page = await (await browser.newContext()).newPage();

const chunks = [];
for (const p of PATCHES) {
  console.log(`fetching ${p.id} …`);
  const grid = await page.evaluate(
    async ({ url, size }) => {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`${url} -> ${res.status}`);
      const blob = await res.blob();
      const bmp = await createImageBitmap(blob);
      const c = new OffscreenCanvas(size, size);
      const g = c.getContext('2d');
      g.drawImage(bmp, 0, 0, size, size);
      const d = g.getImageData(0, 0, size, size).data;
      const out = new Array(size * size);
      let min = Infinity;
      let max = -Infinity;
      for (let i = 0; i < size * size; i++) {
        // DEM tiles encode elevation as luminance.
        const v = 0.299 * d[i * 4] + 0.587 * d[i * 4 + 1] + 0.114 * d[i * 4 + 2];
        out[i] = v;
        if (v < min) min = v;
        if (v > max) max = v;
      }
      const range = Math.max(1, max - min);
      return out.map((v) => Math.round(((v - min) / range) * 1000) / 1000);
    },
    { url: p.url, size: SIZE },
  );
  chunks.push(
    `  '${p.id}': {\n    source: ${JSON.stringify(p.source)},\n    size: ${SIZE},\n    heights: ${JSON.stringify(grid)},\n  },`,
  );
  console.log(`  ok (${grid.length} samples)`);
}

await browser.close();

const file = `/**
 * GENERATED by scripts/fetch-dem.mjs — do not edit by hand.
 * Sources: NASA Trek WMTS (MGS MOLA, LRO LOLA). Public domain (NASA).
 */
import type { DemPatch } from './index.js';

export const GENERATED_DEMS: Record<string, DemPatch> = {
${chunks.join('\n')}
};
`;
const out = join(here, '..', 'packages', 'engine', 'src', 'world', 'dem', 'generated.ts');
writeFileSync(out, file);
console.log('wrote', out, '- rebuild the engine to embed the patches.');
