import { Material, type MaterialDef, type ResourceKey } from '../types.js';

export const MATERIALS: Record<Material, MaterialDef> = {
  [Material.Air]: {
    id: Material.Air,
    name: 'Air',
    hardness: 0,
    yields: null,
    colors: ['#000000', '#000000', '#000000'],
    jitter: 0,
  },
  [Material.Regolith]: {
    id: Material.Regolith,
    name: 'Regolith',
    hardness: 2,
    yields: { resource: 'regolith', amount: 1 },
    colors: ['#b3a08a', '#8a7a68', '#6e6154'],
    jitter: 0.06,
  },
  [Material.Rock]: {
    id: Material.Rock,
    name: 'Rock',
    hardness: 4,
    yields: { resource: 'stone', amount: 1 },
    colors: ['#9a9188', '#726b64', '#575049'],
    jitter: 0.05,
  },
  [Material.Basalt]: {
    id: Material.Basalt,
    name: 'Basalt',
    hardness: 6,
    yields: { resource: 'stone', amount: 2 },
    colors: ['#5d5a5e', '#454347', '#333136'],
    jitter: 0.04,
  },
  [Material.Ice]: {
    id: Material.Ice,
    name: 'Water ice',
    hardness: 3,
    yields: { resource: 'ice', amount: 2 },
    colors: ['#cfe6ef', '#9dc2d4', '#7ba3b8'],
    jitter: 0.05,
  },
  [Material.IronOre]: {
    id: Material.IronOre,
    name: 'Iron ore',
    hardness: 5,
    yields: { resource: 'iron', amount: 2 },
    colors: ['#8f6f5c', '#6d5244', '#513c31'],
    jitter: 0.09,
  },
  [Material.Silica]: {
    id: Material.Silica,
    name: 'Silica sand',
    hardness: 2,
    yields: { resource: 'silica', amount: 2 },
    colors: ['#d8cbb2', '#b1a58f', '#8e8471'],
    jitter: 0.05,
  },
  [Material.CopperOre]: {
    id: Material.CopperOre,
    name: 'Copper ore',
    hardness: 5,
    yields: { resource: 'copper', amount: 2 },
    colors: ['#7f9184', '#5e7365', '#48594e'],
    jitter: 0.1,
  },
  [Material.TitaniumOre]: {
    id: Material.TitaniumOre,
    name: 'Titanium ore',
    hardness: 7,
    yields: { resource: 'titanium', amount: 1 },
    colors: ['#aab4bd', '#7e8992', '#616b74'],
    jitter: 0.08,
  },
  [Material.Crystal]: {
    id: Material.Crystal,
    name: 'Crystal',
    hardness: 8,
    yields: { resource: 'crystal', amount: 1 },
    colors: ['#b48fd9', '#8b64b3', '#6c4a91'],
    jitter: 0.12,
  },
  [Material.Dust]: {
    id: Material.Dust,
    name: 'Fine dust',
    hardness: 1,
    yields: { resource: 'regolith', amount: 1 },
    colors: ['#c9b9a0', '#a2937d', '#847763'],
    jitter: 0.04,
  },
  [Material.Sulfur]: {
    id: Material.Sulfur,
    name: 'Sulfur deposit',
    hardness: 3,
    yields: { resource: 'sulfur', amount: 2 },
    colors: ['#d6c05a', '#ab9743', '#8a7a35'],
    jitter: 0.1,
  },
};

export const RESOURCE_NAMES: Record<ResourceKey, string> = {
  regolith: 'Regolith',
  stone: 'Stone',
  ice: 'Water ice',
  iron: 'Iron',
  silica: 'Silica',
  copper: 'Copper',
  titanium: 'Titanium',
  crystal: 'Crystal',
  sulfur: 'Sulfur',
};
